{% set name = "ilastik-napari" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8e971a70389f9257eaca7561637301f996f316fdff2cb223c5828d162970bec4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - napari
    - numpy >=1.20
    - python >=3.8
    - qtpy
    - scikit-learn
    - sparse

test:
  imports:
    - ilastik
    - ilastik.napari
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ilastik/ilastik-napari
  summary: ilastik plugin for napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
